/**********************************************************************************************************************
 * \file CCU6_Interrupt.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "IfxPort.h"
#include "IfxCcu6_Timer.h"
#include "CCU6_Interrupt.h"
#include "GTM_ATOM_PWM.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define ISR_PRIORITY_CCU6_INT1  40                                          /* Priority for interrupt ISR           */
#define CCU6_TIMER_FREQ         48828                                       /* Timer module frequency in Hz         */
#define CCU6_ISR_FREQ           50                                   /* ISR frequency in Hz                  */
#define CCU6_TIMER_PERIOD       (CCU6_TIMER_FREQ / CCU6_ISR_FREQ) - 1
#define MOTOR_PI_STEP_LIMIT     80
#define MOTOR_PI_KP_NUM         1
#define MOTOR_PI_KP_DEN         4
#define MOTOR_PI_KI_NUM         1
#define MOTOR_PI_KI_DEN         8


/* CCU6 */
#define CCU6                    &MODULE_CCU60                               /* CCU6 will be used in this example    */
#include "IfxGpt12.h"

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
IfxCcu6_Timer g_timer;                                                      /* Timer structure                      */
uint16 g_counter = 0;                                                        /* Variable to keep count of ISR calls  */
volatile sint16 MotorTargetDuty = 0;
volatile sint16 MotorLTargetDuty = 0, MotorRTargetDuty = 0;
volatile sint16 MotorL_Duty = 0, MotorR_Duty = 0;
static sint16 motorLLastError = 0;
static sint16 motorRLastError = 0;
/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
void initCCU6(void);

static sint16 MotorDutyPiUpdate(sint16 duty, sint16 target, sint16 *lastError)
{
    sint16 error;
    sint32 step;

    error = target - duty;
    step = ((sint32)(error - *lastError) * MOTOR_PI_KP_NUM) / MOTOR_PI_KP_DEN;
    step += ((sint32)error * MOTOR_PI_KI_NUM) / MOTOR_PI_KI_DEN;

    if((error != 0) && (step == 0))
    {
        step = (error > 0) ? 1 : -1;
    }

    if(step > MOTOR_PI_STEP_LIMIT)
    {
        step = MOTOR_PI_STEP_LIMIT;
    }
    else if(step < -MOTOR_PI_STEP_LIMIT)
    {
        step = -MOTOR_PI_STEP_LIMIT;
    }

    if((error > 0) && (step > error))
    {
        step = error;
    }
    else if((error < 0) && (step < error))
    {
        step = error;
    }

    *lastError = error;
    return (sint16)(duty + step);
}
/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
/* Macro to define Interrupt Service Routine.
 * This macro makes following definitions:
 * 1) Define linker section as .intvec_tc<vector number>_<interrupt priority>.
 * 2) define compiler specific attribute for the interrupt functions.
 * 3) define the Interrupt service routine as ISR function.
 *
 * IFX_INTERRUPT(isr, vectabNum, priority)
 *  - isr: Name of the ISR function.
 *  - vectabNum: Vector table number.
 *  - priority: Interrupt priority. Refer Usage of Interrupt Macro for more details.
 */
IFX_INTERRUPT(isrCCU6Timer, 0, ISR_PRIORITY_CCU6_INT1);
extern sint16 SpeedL,SpeedR;


void isrCCU6Timer(void)
{
    sint16 cnt_l = 0,cnt_r = 0;
    // 获取当前计数
    cnt_l = (sint16)IfxGpt12_T2_getTimerValue(&MODULE_GPT120);
    cnt_r = (sint16)IfxGpt12_T6_getTimerValue(&MODULE_GPT120);
    // 清零计数�?
    IfxGpt12_T2_setTimerValue(&MODULE_GPT120,0);
    IfxGpt12_T6_setTimerValue(&MODULE_GPT120,0);
    // 车速计�?
    SpeedL = cnt_l;
    SpeedR = cnt_r;
    //PID车速控�?

    //控制命令发�?
    MotorL_Duty = MotorDutyPiUpdate(MotorL_Duty, MotorLTargetDuty, &motorLLastError);
    MotorR_Duty = MotorDutyPiUpdate(MotorR_Duty, MotorRTargetDuty, &motorRLastError);
    MotorControl(MotorL_Duty,MotorR_Duty);

}

/* Function to initialize CCU6 module */
void initCCU6(void)
{
    IfxCcu6_Timer_Config timerConfig;                   /* Structure for timer configuration                        */
    IfxCcu6_Timer_initModuleConfig(&timerConfig, CCU6); /* Initialize the timer module structure with default values*/

    /* The Serial Peripheral Bus has a default Frequency of Fcc6 = 100000000 Hz = 100 MHz
     * Possible frequencies for the CCU6 timer are:
     *       - 100000000 Hz = 100 MHz   (Fcc6)
     *       - 50000000 Hz  = 50 MHz    (Fcc6/2)
     *       - 25000000 Hz  = 25 MHz    (Fcc6/4)
     *       - 12500000 Hz  = 12.5 MHz  (Fcc6/8)
     *       - 6250000 Hz   = 6.25 MHz  (Fcc6/16)
     *       - 3125000 Hz   ~ 3 MHz     (Fcc6/32)
     *       - 1562500 Hz   ~ 1.5 MHz   (Fcc6/64)
     *       - 781250 Hz    ~ 780 KHz   (Fcc6/128)
     *       - 390625 Hz    ~ 390 KHz   (Fcc6/256)
     *       - 195312.5 Hz  ~ 200 KHz   (Fcc6/512)
     *       - 97656.25 Hz  ~ 100 KHz   (Fcc6/1024)
     *       - 48828.12 Hz  ~ 50 KHz    (Fcc6/2048)
     *       - 24414.06 Hz  ~ 25 KHz    (Fcc6/4096)
     *       - 12207.03 Hz  ~ 12.5 KHz  (Fcc6/8192)
     *       - 6103.51 Hz   ~ 6 KHz     (Fcc6/16384)
     *       - 3051.75 Hz   ~ 3 KHz     (Fcc6/32768)
     */
    timerConfig.base.t12Frequency = CCU6_TIMER_FREQ;                /* Configure the frequency of the timer module */
    timerConfig.base.t12Period = CCU6_TIMER_PERIOD;                 /* Configure the period of the timer (16-bit)  */
    timerConfig.timer = IfxCcu6_TimerId_t12;                        /* Select the timer to be started              */
    timerConfig.interrupt1.source = IfxCcu6_InterruptSource_t12PeriodMatch; /* Set interrupt source                */
    timerConfig.interrupt1.priority = ISR_PRIORITY_CCU6_INT1;       /* Set the priority of the ISR                 */
    timerConfig.interrupt1.typeOfService = IfxSrc_Tos_cpu0;         /* Set the type of service for the interrupt   */
    timerConfig.trigger.t13InSyncWithT12 = FALSE;                   /* Configure timers synchronization            */

    IfxCcu6_Timer_initModule(&g_timer, &timerConfig);               /* Initialize the CCU6 module                  */
}

/* Function to start the CCU6 timer */
void startCCU6(void)
{
    IfxCcu6_Timer_start(&g_timer);                                  /* Start the timer                             */
}
