/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "ERU_Interrupt.h"
#include "GPT12_Timer_Interrupt.h"
#include "GTM_ATOM_PWM.h"
#include "Bsp.h"
#include "LQ_TFT18.h"
#include "LQ_CAMERA.h"
#include "IfxGpt12.h"
#include <stdint.h>
#include "ADC_Background_Scan.h"
#include "CCU6_Interrupt.h"



IfxCpu_syncEvent cpuSyncEvent = 0;
uint16 adc_value;
sint16 Steer = 0;
uint16_t cnt;
sint16 SpeedL = 0,SpeedR = 0;

void core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&cpuSyncEvent);
    IfxCpu_waitEvent(&cpuSyncEvent, 1);
    initPeripheralsAndERU();

//init_ASCLIN_UART();
//send_receive_ASCLIN_UART_message();
    initADC();
//显示屏测试
    TFTSPI_Init(0);     // 先初始化屏幕，0/1 对应横竖屏
    TFTSPI_CLS(u16BLACK);

//眨眼测试
//    Test_Ayanami();
    //Test_TFT18();




//电机舵机初始化
    initGtmATomPwm();
//    ServoControl(0);

    initADC();
//车速采集控制模块
    initGpt12Timer();
    initCCU6();
    startCCU6();
    CAMERA_Init(50);

    TFTSPI_P6X8Str(0,0,"Here Comes a New Challenger!",u16WHITE,u16BLACK);

    while(1)
    {
        if(Camera_Flag == 2){//图像采集完成
        Get_Use_Image();
        Camera_Flag = 0;
        TFTSPI_Road(0,0,120,160,(uint8 *)Image_Use);
        }

        //adc_value = readADCValue(0);
//        cnt = IfxGpt12_T2_getTimerValue(&MODULE_GPT120);
        adc_value = readADCValue(0);
        ServoControl(Steer);

        //不要停下来模式MotorControl(MotorL_Duty,MotorR_Duty);

//        waitTime(IfxStm_getTicksFromMilliseconds(BSP_DEFAULT_TIMER, 100));
    }
}
