/**********************************************************************************************************************
 * \file GPT12_Timer_Interrupt.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "GPT12_Timer_Interrupt.h"
#include "Ifx_Types.h"
#include "IfxGpt12.h"
#include "IfxPort.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Function Implementations-----------------------------------------------*/
/*********************************************************************************************************************/

/* Function to initialize the GPT12 and start the timer */
void initGpt12Timer(void)
{
    /* Initialize the GPT12 module */
    IfxGpt12_enableModule(&MODULE_GPT120);                                          /* Enable the GPT12 module      */
    IfxGpt12_setGpt1BlockPrescaler(&MODULE_GPT120, IfxGpt12_Gpt1BlockPrescaler_4); /* Set GPT1 block prescaler     */
    IfxGpt12_setGpt1BlockPrescaler(&MODULE_GPT120, IfxGpt12_Gpt2BlockPrescaler_2); /* Set GPT1 block prescaler     */


    /* Initialize the Timer T2 */
    IfxGpt12_initTxInPin(&IfxGpt120_T2INB_P33_7_IN,IfxPort_InputMode_pullUp);
    IfxGpt12_initTxEudInPin (&IfxGpt120_T2EUDB_P33_6_IN,IfxPort_InputMode_pullUp);
    IfxGpt12_T2_setCounterInputMode(&MODULE_GPT120,IfxGpt12_CaptureInputMode_bothEdgesTxIN);
    IfxGpt12_T2_setDirectionSource(&MODULE_GPT120,IfxGpt12_TimerDirectionSource_external);
    IfxGpt12_T2_setEudInput(&MODULE_GPT120,IfxGpt12_EudInput_B);
    IfxGpt12_T2_setInput(&MODULE_GPT120,IfxGpt12_Input_B);
    IfxGpt12_T2_setMode(&MODULE_GPT120,IfxGpt12_Mode_counter);
    IfxGpt12_T2_setTimerDirection (&MODULE_GPT120,IfxGpt12_TimerDirection_up);

    IfxGpt12_T2_run(&MODULE_GPT120, IfxGpt12_TimerRun_start);                       /* Start the timer              */

    /* Initialize the Timer T6 */
    IfxGpt12_initTxInPin(&IfxGpt120_T6INA_P20_3_IN,IfxPort_InputMode_pullUp);
    IfxGpt12_initTxEudInPin (&IfxGpt120_T6EUDA_P20_0_IN,IfxPort_InputMode_pullUp);
    IfxGpt12_T6_setCounterInputMode(&MODULE_GPT120,IfxGpt12_CaptureInputMode_bothEdgesTxIN);
    IfxGpt12_T6_setDirectionSource(&MODULE_GPT120,IfxGpt12_TimerDirectionSource_external);
    IfxGpt12_T6_setEudInput(&MODULE_GPT120,IfxGpt12_EudInput_A);
    IfxGpt12_T6_setInput(&MODULE_GPT120,IfxGpt12_Input_A);
    IfxGpt12_T6_setMode(&MODULE_GPT120,IfxGpt12_Mode_counter);
    IfxGpt12_T6_setTimerDirection (&MODULE_GPT120,IfxGpt12_TimerDirection_down);

    IfxGpt12_T6_run(&MODULE_GPT120, IfxGpt12_TimerRun_start);                       /* Start the timer              */

}

