/**********************************************************************************************************************
 * \file GTM_ATOM_PWM.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "GTM_ATOM_PWM.h"
#include "Ifx_Types.h"
#include "IfxGtm_Atom_Pwm.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define MOTOR_L_P          IfxGtm_ATOM0_7_TOUT64_P20_8_OUT
#define MOTOR_L_N          &MODULE_P21,5
#define MOTOR_R_P          IfxGtm_ATOM0_2_TOUT55_P21_4_OUT
#define MOTOR_R_N          &MODULE_P21,3
#define MOTOR_PERIOD       10000


#define SERVO              IfxGtm_ATOM2_5_TOUT35_P33_13_OUT      /* 舵机 which will be driven by the PWM              */
#define SERVO_LEFT_MAX     160000
#define SERVO_MID          145000
#define SERVO_RIGHT_MAX    130000
/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
IfxGtm_Atom_Pwm_Config g_atomConfig;                            /* Timer configuration structure                    */
IfxGtm_Atom_Pwm_Driver g_atomDriver[3];                            /* Timer Driver structure                           */                                        /* Initialization of the fade direction variable    */
uint32 Servo_cali = SERVO_MID;
/*********************************************************************************************************************/
/*-----------------------------------------------Function Prototypes-------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Function Implementations-----------------------------------------------*/
/*********************************************************************************************************************/
/* This function initializes the ATOM */
void initGtmATomPwm(void)
{
    IfxPort_setPinState(MOTOR_L_N, IfxPort_State_low);
    IfxPort_setPinMode(MOTOR_L_N, IfxPort_Mode_outputPushPullGeneral);            /* Initialize LED port pin          */
    IfxPort_setPinState(MOTOR_R_N, IfxPort_State_low);
    IfxPort_setPinMode(MOTOR_R_N, IfxPort_Mode_outputPushPullGeneral);            /* Initialize LED port pin          */

    IfxGtm_enable(&MODULE_GTM); /* Enable GTM */

//    IfxGtm_Cmu_setClkFrequency(&MODULE_GTM, IfxGtm_Cmu_Clk_0, CLK_FREQ);        /* Set the CMU clock 0 frequency    */
    IfxGtm_Cmu_enableClocks(&MODULE_GTM, IFXGTM_CMU_CLKEN_CLK0);                /* Enable the CMU clock 0           */

    IfxGtm_Atom_Pwm_initConfig(&g_atomConfig, &MODULE_GTM);                     /* Initialize default parameters    */
    //舵机初始�?
    g_atomConfig.atom = SERVO.atom;                                       /* Select the ATOM depending on the LED     */
    g_atomConfig.atomChannel = SERVO.channel;                             /* Select the channel depending on the LED  */
    g_atomConfig.period = 1e6;                                            /* Set timer period                         */
    g_atomConfig.dutyCycle = SERVO_MID;
    g_atomConfig.pin.outputPin = &SERVO;                                  /* Set LED as output                        */
    g_atomConfig.synchronousUpdateEnabled = TRUE;                       /* Enable synchronous update                */

    IfxGtm_Atom_Pwm_init(&g_atomDriver[0], &g_atomConfig);                 /* Initialize the PWM                       */
    IfxGtm_Atom_Pwm_start(&g_atomDriver[0], TRUE);                         /* Start the PWM                            */

    //左电机初始化
    g_atomConfig.atom = MOTOR_L_P.atom;                                       /* Select the ATOM depending on the LED     */
    g_atomConfig.atomChannel = MOTOR_L_P.channel;                             /* Select the channel depending on the LED  */
    g_atomConfig.period = MOTOR_PERIOD;                                            /* Set timer period                         */
    g_atomConfig.dutyCycle = 0;
    g_atomConfig.pin.outputPin = &MOTOR_L_P;                                  /* Set LED as output                        */
    g_atomConfig.synchronousUpdateEnabled = TRUE;                       /* Enable synchronous update                */

    IfxGtm_Atom_Pwm_init(&g_atomDriver[1], &g_atomConfig);                 /* Initialize the PWM                       */
    IfxGtm_Atom_Pwm_start(&g_atomDriver[1], TRUE);

    //右电机初始化
    g_atomConfig.atom = MOTOR_R_P.atom;                                       /* Select the ATOM depending on the LED     */
    g_atomConfig.atomChannel = MOTOR_R_P.channel;                             /* Select the channel depending on the LED  */
    g_atomConfig.period = MOTOR_PERIOD;                                            /* Set timer period                         */
    g_atomConfig.dutyCycle = 0;
    g_atomConfig.pin.outputPin = &MOTOR_R_P;                                  /* Set LED as output                        */
    g_atomConfig.synchronousUpdateEnabled = TRUE;                       /* Enable synchronous update                */

    IfxGtm_Atom_Pwm_init(&g_atomDriver[2], &g_atomConfig);                 /* Initialize the PWM                       */
    IfxGtm_Atom_Pwm_start(&g_atomDriver[2], TRUE);

}

/* 舵机This function sets the duty cycle of the PWM */
void ServoControl(sint16 steer)
{
    uint32 duty;

    if(steer < -100)
    {
        steer = -100;
    }
    else if(steer > 100)
    {
        steer = 100;
    }

    if(steer < 0)
    {
        duty = steer * (SERVO_MID - SERVO_LEFT_MAX) / 100 + SERVO_MID;
    }
    else
    {
        duty = steer * (SERVO_RIGHT_MAX - SERVO_MID) / 100 + SERVO_MID;
    }
    IfxGtm_Atom_Ch_setCompareOneShadow(g_atomDriver[0].atom,g_atomDriver[0].atomChannel,duty);
}

/* 电机This function sets the duty cycle of the PWM */
void MotorControl(sint16 motor_l,sint16 motor_r)
{
    uint32 duty_l,duty_r;
    //*******左电�?******//
    //范围限制
    if(motor_l < -MOTOR_PERIOD)
    {
        motor_l = -MOTOR_PERIOD;
    }
    else if(motor_l > MOTOR_PERIOD)
    {
        motor_l = MOTOR_PERIOD;
    }
    //占空�?
    if(motor_l < 0)
    {
        duty_l = motor_l + MOTOR_PERIOD;
        IfxPort_setPinState(MOTOR_L_N, IfxPort_State_high);
    }
    else
    {
        duty_l = motor_l;
        IfxPort_setPinState(MOTOR_L_N, IfxPort_State_low);
    }

    //*******右电�?******//
        //范围限制
        if(motor_r < -MOTOR_PERIOD)
        {
            motor_r = -MOTOR_PERIOD;
        }
        else if(motor_r > MOTOR_PERIOD)
        {
            motor_r = MOTOR_PERIOD;
        }
        //占空�?
        if(motor_r < 0)
        {
            duty_r = motor_r + MOTOR_PERIOD;
            IfxPort_setPinState(MOTOR_R_N, IfxPort_State_high);
        }
        else
        {
            duty_r = motor_r;
            IfxPort_setPinState(MOTOR_R_N, IfxPort_State_low);
        }
    IfxGtm_Atom_Ch_setCompareOneShadow(g_atomDriver[1].atom,g_atomDriver[1].atomChannel,duty_l);
    IfxGtm_Atom_Ch_setCompareOneShadow(g_atomDriver[2].atom,g_atomDriver[2].atomChannel,duty_r);

}
